### ISSUE TITLE
unable to load omssa identifications in FA ver 1.5.15

### ISSUE THREAD

**Issue by bhanu2008** [compomics/fragmentation-analyzer#4]
Hello Herald,
I am working with latest release 1.5.15. although am I able to successfully load the .omx files, it is stopping at loading identifications step. I alloted around 20GB RAM so it is not processor problem.
[FA 1.5.15 screenshot.docx](https://github.com/compomics/fragmentation-analyzer/files/1130434/FA.1.5.15.screenshot.docx). please do the needful.
Regards
Bhanu

**Comment by hbarsnes** [comment]
Hi Bhanu,

Thanks for telling us about this. I can confirm that I see the same problem on my side. It is related to the loading of the OMSSA modification files. I will look into it and get back to you.

Best regards,
Harald

**Comment by bhanu2008** [comment]
Hi Herald,
Thanks for quick response. 
Regards
Bhanu

**Comment by hbarsnes** [comment]
Hi Bhanu,

I just released [Fragmentation Analyzer v1.5.16](http://genesis.ugent.be/maven2/no/uib/FragmentationAnalyzer/1.5.16/FragmentationAnalyzer-1.5.16.zip) which should solve the problem of loading data from OMSSA omx files. If this is not the case, please let me know and I'll reopen the issue.

Best regards,
Harald
